---
apiVersion: batch/v1
kind: Job
metadata:
  name: node-collector
spec:
  template:
    metadata:
      labels:
        app: node-collector
    spec:
      dnsPolicy: ClusterFirst
      hostPID: true
      automountServiceAccountToken: true
      containers:
        - name: node-collector
          image: ghcr.io/aquasecurity/node-collector:e2e
          command:
            - node-collector
          args:
            - k8s
            - --kubelet-config
            - QlpoOTFBWSZTWevsTlkAB7//gFZUQABSB//wP+/+qr////pgBl8e9AzvbazT3vedm6vddOmuoShCJiMKntPSTFP1NJ5J6ZQZDEaaaaNA9Q9TQZECNGU2qemJI9qnqP1E9TQeoDQaMgAaAGmgVPKg9RoAGmmgAAAAAGgASmRJpCTNCHpNGymmmhoDTTIDQAGhoOGmmRiMJpgIYBNMIwTEyGmRoaASJBAKeQpqenqn6m1J6jyNqjag9EyNNMjTam9UHotM2AkNoA78MgRDEJQvkM/WPPSkMCG2xohqJzopTGEOVUIQLIEAc4hC927D4sZxiD39nt9ulBS/iJNG+3jI78KnTkPpU+74dDeu/lSNSiIM0Z9fZnA2mv2jZrXcqyOZqmVVSxH5TFklL/czJUgSqOCrBmmrxMTT1cOlC+G4et+VUyNnjs1PRtm2gEd9tnFCE3CQSogkQDFEeFEqPAoKFCQIsNwkmiIQoE2KNO93s/CmbFOq4pahYOpUjZajz0ybb9OhpNjFA08bX4PvhhdNS5QNzMRZBxo8imnsHWvHIiHuaf5p3rKyb8XJITvaxEnRAlapzG2jD0TOw9HXOWz7FzG7DHAJELQroMRxJXAq8dIyIaukpWTlU5UhNjGuK4kiQN+oZgQqK4JlIIms81OkY1tHOlIVH303TFFWahSi6zRViiv+rN6XCELH3CNBdvGekDOzsrbr2z+LP4aufwXw+qB1GksHgYLaKl7Z8Tn7edmvWDrQsEK4724Qffa64gUByBYLRNt2Drdj4t5ucVaddDkE7zdyDEz+Rf4BkZOtPjYWx/wFJaas5YJG8bDVcLi1qJNxqq1yqqw5uKerHhdnxn70W5zKPSi+tSf2JTUrUz3W3HlhGGCOrqtszGoh+2NYZeevb+hsQIidcQcxjYJ3gT6cltL7mDJB8XPIgciXgOmLfHXNlk0qy7TlAvNZ969i8QusBi5l6F8F5ScxvuF5QM+p7U9yBm3cQUXLv2UN4Wod39dileLcRgu6q3LRH0BZCUs3po2FToWcJc2l0n+Xkhf4HB4bJDeLhh6DQUCeQA1LsAL+3tmYiv+n15KsmNVtuGVVS2aLXbYUDODksmi0fRRwiKDwbd3DBE09MZMKrKVIHM2Dk0C7W9IClEo25aAxQc4SizkWNnkWJmENYzVsBUnEIxQlHSZ7b6y6+IPHaq6ofLrVjbcMixcvNLtDKFnZF9GjTqOcrlOjyqtcVwmrGUzlRBySSwsRyWIRvQGQKYiXGkKVGkgUk8TKGCoGBMjojEyjOp4eMFB/nEDZvFC/JBFwlMgLiguoS+i46AvWgKjECO3ijAMb6aIXCzZMh7pUGQ7JBgsotmLd7TtEIFilDQXAjokrpB1S9ixmy0q9GGJL5DMjk3JI8cbDMxauW8VJyF7oySm2Z1obghYw1KQKjzz4MdXBwmB+uoanar9l4MwDlEdx9lRS0ba9gwU0TlFFG6T7iglRoHIFUE6tTyqQ3ckONIIUJBmRdxdUVFRuYRraMMu07trPVJHBajAvQJ2rHnO0qOHR7fciKjEroH0PALdjkphhdKYGPPeatBzVmsP1KMUTh5SSUEwGSDpyTmLrrtsDz1Dx51ExSCLWio8Z5ikycEoignIiwGI82bOnJgE0aNWzsLER8CzaE6PpSjoJUlgRSBXhT681RgQY5OPtY5wlEsVzW01kmeCRRRnmbEdWIiSxchhvHGMJwg1EzzfuwvEtU2CUArIqN9tYfrIgLwsm5tJHoHG/X911KMxZBJU4ZJi2nVLQ26X7WLxT3mQTSljy0vgx01vZdqXIYkmwwEGmEgm3NJGfhINKO0ostFldiDf3cb11JWomlCELAZntiuykEtUlt0J3FYJGGm7yUON0LRO3xq9ZSZPXIqeupblbYqkEjNl0zmlV5luos1UFSvmCgrHiQFGK4vQC1gaDNYASCuhLRQ0iYcipOcTJA2bUnX+IghZZLDM4Y88wzM0doK0QfJL2Pp/JmRq6TA6HpNHqagusTl6+K6tIDkoBjIUpF4yRxXDDJW45WFu8BIgdbEVNLWj7GZOSnKJjW7ThiRoYC09/OJflN+/v4Kg84f8XckU4UJDr7E5Z
            - --kubelet-config-mapping
            - QlpoOTFBWSZTWRI2lT4AABtfgAAQWAfiNS+q/gA/79/wQAH1NxTuYaCmU09Ieo00ek9RoNAAGg0Epoppop5Eep+qNAeoGmjQPTSDQSSoaaek/VPU0ADQAAAAEkRAU8apsJMRoGjTQAPU9TcRXr86hZoteI/I2xvvr+qjmYb5eywfOzdw20qKFKDyTK+y+UVQlMiNJbY1T6P1unARCw9VNa/FDzMKZmhoyMSDEiqjQPhrffDzOcTiBP5D5e9ZcVSQbFkmZrdMO0E5nJdnKswNeV05HRGheGqz+OkvOsQ+SNzM/wdP+EljWhKpZ2s6FPMBKQ4ooKM5WbC1MbJni7FGg4dUVHNjB5jcaTn2QIISxqyNxcCkMWwIZnaL4Lle0jr4vMCYErt1RtISC8Amd2EmT7OcFGy4ZWjJiWsIFowOAMZp2XAnxMhVFCGZwkInZCZCliWxlXZXxp8SkQlpjctTMw0jFSyk8QVo5HxHKhWUUl5EApTfyYmz76vSgrSCglssOTQwoEwBdgTE0dp5k/BMVlg+oeZ5RamSfpwhQ4rgr4yRdQH0gFjDQ4MbhYbAwAQxJCV6K9WSlGMkw5wV9WqJoZnh4EQdQ7QkgQMmt0A7DUAcvdrMEJEy0LiTcQlc07o9NhpJ8gXEYAjA6AV+oNcU3TgaZYE98KfZySyKLaz/F3JFOFCQEjaVPg==
            - --node-config
            - QlpoOTFBWSZTWfJTw/cAArlbgFAQWAf8VwAAv//f4FAF+9U82RpGiwWWyW22Yw0Mhpk0AxDTTRoaMMNDIaZNAMQ000aGjBJpJJoUNMjRp6mTQDTQBFIImamhkm0mU9NE09QPSBEkCITaAqZGgaAAySBDrk6J3/Gz5vhtdvpLa6tT/edc/GZq04bJDNarV8mISEhIfzezcsZyaxYcatYtbkXzp0PCuS1bwyY6pXV84eVz0cV4U7CTeR1wrblV9rWNpgnqcIir4FFNhfRJFmGoCqRZFBRYpFVQWKQFiyAOosWy29S0x4vbsBs5sJt4ydIdFngJP3g97xHLcFuoiPVYJU3AZHLxE47xTrDQTo0PUjNqE/sXg9AlTZ4gZwLysfHNG/2i0ixXOjrRiv1C8Obw4LQ0Yoz8Sv6N8NOt85Khoym7N5bxwuWZDWa1PHe8DazW2TnF6lFJkh6c8lyjNold0paJzbkDWJ2HQgBe3wVvA4P4DXXY3TI5gyZgatQ2qq+pg5kIXIQSOVpw5lQl3cCidpIKGlHduoVzNkN8mDYI7i6QomC9iksAUY2qYEJK8IUo0UT8Dxcx7I+HfUhCEJf9khigDYvC/Hntw8ZnmoQNpXBTa3gXcD2WIF6KztV1+D6r+coTfSmhjIPSd2jZlkBQkDcjxLnmTXgo6o4iwo8yiJ3A2U8iJipjN2s81CW0V8oonySvEA2PAW2BEN1RS4Am1NVchb1ofKwdVeIG+IYhRhUrM2xFV30ByJrQwPX5m1LC4LMX0DS4JIUbpLoARWiYN+20u7iEgmriUHRkrij3U9oVZNHIoDlOJrV7Cwi5nN+Vb1Dici4FL8xA3ASPQ5BPkIkORuXu6uSExHK221bbbaWlFVXRLWkvZCXvey7tZRHCvZ6guUR+1RyK2JID6EA+UhADvbuiPBAH0od1HmWBTwbbWHADzIIVAwgxubA6ReZsXfR8HQV9cAEFo6KPk6gp0Yecw8+Tqr6Oy3Q9O/dO/2IycrqTJ69yXdB3ICgvEQqRYMTkItGWMp3B7grQpKSlSGZChOFRjgoG8zMTmdNQYFiYKbBXQ0R4JcoTWvFgQyBz3hg4igoKT9s2AOZzkevebQLy2A71FWSAwjk0ncjScSQIRW6PJe6JQvqbkRtcghfVF3PijQhxACEbtQwDBR6GvEyd62VmghmzZI4obtH61dohoia7AdBfdHt8ZQ5DOddKkCjyUFqVG4jvSlAEe0XIvN6CwwprmEwhMoLUXNGwhqLjVWq4SVeiUXseTaw1fDYsMgb5BYLDL8I5DCsDtYYMkKnAhZ2NFvoPfc8+GCePVjiQZJPYBlNK+yqJ9PwLrMyC1hA5NVoqdzS9QJ2tBIRbLTr9RgFYdogGSGmWCMMbKyVydOrCAYiJAJKBSkRwWDFI5MAmCOK8oon0V0ofMXfKwRNOwP4i95AGXUQ/whqoHu7FA/4u5IpwoSHkp4fu
            - --node-commands
            - QlpoOTFBWSZTWZR1SJMABq/fgFAQd/f//y/v/i9/7//+YAm/aAADQAAAAAAAAAMpQAGhoNA0AAA0aaaAAAAAVT8qPGVAAABoAAAAAAAABxoyZGEYgGE0GATQaBkyaMmQwgMcaMmRhGIBhNBgE0GgZMmjJkMIDHGjJkYRiAYTQYBNBoGTJoyZDCAwiSITQBCYCYTU9CmhvUyTRpoaaD1DeomjTalhUQ8wNhD+Z9obn7D7yx8DE4C9XV3d3VVd3Z2SLWlKksMIWRCtKjQRmoCIDMxNmrnyBwAgICKBQIDJJJJwquANXqrfeikRS3n9wQ9aKcaGQfKcx9f5ueO/VolyQ2wqBAIR01dkEt7PSIgL3KKJ7hD3/AhDQgSpJJJNCu1taSTgXLWk1qt0LjIEhxAEqMhDxENSKZ75JJCQkJJJCSTEQ2tlWCGQunTJ5CHGbEDgiPfA0kA5T8tTrueGwoMPPzykyKojzIpDoBLn1Ggo9ZQ+ZyYTEzMDQbzK/ZuhMKqpTUqVKKLVkCGoXdsRTSo1FTdvKRM8aKBLxC+qMhcXoxKDcUaxcQLotrUA5cxCCmxAiMghdXCH3Hk84h7n6H0uL6RD7hCLnxbUMcxhgvlARurFXU6XvY0PtFuh8YBlB1dXkIbuQtRXbCphVGgEzDu0mkZEkAkJFT736F5oQOJ3nwEInbkimhFK9ti0JCQkkAkJEkJ/FFKRLu5jSrvWzvfFweOnEQs4+PTGqqqoseOhwY2fAu5A65Gd7i5ut0ObELwbNlbkdBnUolRcijzolgsGwTMQHsH4aGQYxxlISwmLgdC2PQEzAuulHIF9AIQgEkEkGCDQHscrYZZaRC4mLjWGONhMTWaBDK+WOVhLyr3stqte97WLWtLWt4Ipe177hU6zpRSCnWMIARAiJEToAIUUi0A96HmrbMc33u9N8B+wQ6xDYPzDnWue2i0tCHaUWOIMyxbGjFtJKZCropLdweWHj7TIy8ciqopwNTgGRVfBFOYw0+wwDI0Q7BD/D4iGPVrPVlC05HivwtcKthLuFVq+xWfB/0Rhodx3mi441wwSgj5nwRTDmDP9L7xDIuc+OYcIvCOPwCNrAXg1CqwObl55SBYy5yvIQ/0XNJcOMiu02xkrDCxoKC5EU5ldu3pP0iGZ/sQ9Qh/sQ7TAzANR2rDp5Sg7Q3BR8psDJ6wbh4B+L4S4aA5D8S4GAZ1reY8i6N0TUq9B9JDaNn3NBUqgoPQikM4yP5tEzRTjDW0Rh9ohBD9f5Cg/egeIbD95oVdpygUuLdUuDMZCSXcxg/MeoCGgS3gQh1n16hMBNBAhQmNDzha4vIdcP6AbWg2opCoaDIwwkkkiKZuoMHI4Ipj62w6dQPQdBxyENoUcfRcWQAtDCSFPkx62wKf1RIQBthaQP5FUWqNgsZtplSZXRwILDOgyRTN/tA0gcCAZC5hsDAfAHkEM3uwDJEDM4zajF62SkDSAuo3kAiRCIENBuMZ8sqqJJKKKCFBKkSxa1qqtpgFB7wDeAaH6No5hpFeR9hAjCRnoDuGENYcDTRsYliVdHBGhCRQeo7A5DUPkHMHO3LutAeBR2QDqEPwGgOgLBwVLCmbmi+loTiRS4n2j+DkNoEgQIGIOo0InrEID6yOsRxDSHO88B6g5xWi4GW42HpPYqdYfgimwMesTNQ0gZClBEU+kAK/c+A+gIE70COlE3piCRR2ivEbH0vyMOMXkNYAfmF0U9prDWikA/MUITQilG0IA6mvlp5UUwEsP6goQ8RCEGAnrJ0G4631MoqxxIpcBOG9FKBCmXOBCAQIQOYMkQPQdSzAO4H+7pHqbh2j6Hew5g4WROYMRHeHAbBiAEDXofcF0UsoYjBwB1hDUGAYB0CtD4uSg3CcCB+RA6kUzfrso4onoIoRWEQaDyCA9IQN73EV39QHK+/jRTmwOMHi2oME6QIAQhCCWMNLa7gowohAhAyDE1AegF+RFNj82scH8t5ofckDgHIHecRxMFwOJXAILFBk6kU+cD2AYgGB0h1IpYDN+KJB1FhfUHxfjm9mw9AZu5FT9h8g2bhkNwFwDcj3o8YdKJzBHpoAMQQiKQTMXz4tbk5QxDWQV0dsphBWD3HYBrIdyn/kUgB+h0iGhm6r0UahZZA2nz1hfGcjoGk7UU9vpfa5555Eta2jOUWkqtR2BDD/NG0gBwFe8AKAsAEPxgsiPUicodDgHB3HzGs2o2IjlSBSmhVmvC5ZiMhAtaWWPQ03Ec0UyxxheqrCDaYxtEIjHIOIIWDaq6AMD4hBhgqWC6JgGDfTKJUqIppBsGlWnftwE1xIz5EUyRS46Q37TIcwu+OwGHJYjDaHztP1AH1ERIwRIESMdyKZHSDmFg8BXI5A3bimEwfCEIzg2DaHEGgp5eUTB8qDNUKVsMgHWGsByMiNzI5JYKeQoVLSFjoOAfOilzaHv8IgQDWqftIIHhFQ+4/wIWp4P/xdyRThQkJR1SJM=
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 50m
              memory: 50M
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: var-lib-etcd
              mountPath: /var/lib/etcd
              readOnly: true
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: var-lib-kube-scheduler
              mountPath: /var/lib/kube-scheduler
              readOnly: true
            - name: var-lib-kube-controller-manager
              mountPath: /var/lib/kube-controller-manager
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: lib-systemd
              mountPath: /lib/systemd/
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
            - name: etc-cni-netd
              mountPath: /etc/cni/net.d/
              readOnly: true
      restartPolicy: Never
      securityContext:
        runAsGroup: 0
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: /var/lib/etcd
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: var-lib-kube-scheduler
          hostPath:
            path: /var/lib/kube-scheduler
        - name: var-lib-kube-controller-manager
          hostPath:
            path: /var/lib/kube-controller-manager
        - name: etc-systemd
          hostPath:
            path: /etc/systemd
        - name: lib-systemd
          hostPath:
            path: /lib/systemd
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
        - name: etc-cni-netd
          hostPath:
            path: /etc/cni/net.d/
